### ISSUE TITLE
vsc.utils.run:run behaves weirdly when command contains empty string

### ISSUE THREAD

**Issue by MatthiasCoppens** [hpcugent/vsc-base#304]
When running a command that's a list that contains an empty string, `run` appears to cut off the command at the empty string.
I'd expect `run(command)` to do the same as `run([word for word in command if word])`.

**Comment by stdweird** [comment]
empty string is passed as empty arg, nothing else
what were you running?

**Comment by boegel** [comment]
@stdweird The value of the `--pass` option was blindly being added to the backend command in jobcli (that's being fixed in https://github.com/hpcugent/jobcli/pull/157).

I told @MatthiasCoppens to open an issue here too on this though, since we should probably disallow empty string values being passed in the list to `run`?

**Comment by stdweird** [comment]
why would we not allow that? empty args do occur and typically have meaning.

**Comment by boegel** [comment]
Right, ok. In this case it was a bug in `jobcli` then, so closing.
